version: '2'
services:
  zookeeper:
    container_name: bootiful-dress-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
      container_name: bootiful-dress-kafka
      image: wurstmeister/kafka:0.10.1.1
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        #Enable Automatic topics creation, topic dresses will have 1 partition and 1 replica, ratings will have 1 partition
        KAFKA_CREATE_TOPICS: "dresses:1:1,ratings:1:1"
        #Expose JMX port and enable JMX for monitoring purposes
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      depends_on:
        - zookeeper

  postgresdb:
    container_name: bootiful-dress-datastore
    image: postgres:9.6.3
    ports:
         - "5432:5432"
    environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=demo
    command: postgres

  dress-service:
    container_name: bootiful-dress-service
    build: build/libs
    image: spring-cloud-stream-kafka
    depends_on: # dress-datastore will be started before the bootiful-dress-service
      - postgresdb
    ports:
      - "9000:9000"
    links:
      - postgresdb
    environment:
      - SPRING_PROFILES_ACTIVE=docker